# Generated by Django 4.2.13 on 2024-07-07 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("food_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="food_app.foodcategory",
            ),
            preserve_default=False,
        ),
    ]
