# Generated by Django 4.2.13 on 2024-07-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
        ("food_app", "0002_food_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="food_app.food"
                    ),
                ),
            ],
            options={
                "db_table": "order_item",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipping_cost", models.PositiveIntegerField()),
                ("total_cost", models.PositiveIntegerField()),
                ("is_pending", models.BooleanField(default=True, editable=False)),
                ("finish_time", models.DateTimeField(editable=False, null=True)),
                ("is_successful", models.BooleanField(default=True, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_app.address",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user_profile.profile",
                    ),
                ),
                ("items", models.ManyToManyField(to="food_app.orderitem")),
            ],
            options={
                "db_table": "order",
            },
        ),
    ]
