# Generated by Django 4.2.13 on 2024-07-11 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_app", "0003_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="finish_time",
            new_name="deliver_time",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_pending",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_successful",
        ),
    ]
